### ISSUE TITLE
Gremlin not detecting hdfs properly. 

### ISSUE THREAD

**Issue by AlexanderDaw** [thinkaurelius/faunus#129]
in gremlin shell, hdfs.ls() lists the contents of the local root users home directory. hdfs.copyFromLocal() copies data to whatever directory I have started the gremlin shell from.. Additionally , even if I use hadoop dfs -cp to move files onto hdfs, gremlin is unable to find the resources when I try to configure faunus.input.location=graph-of-the-gods.json  in the hdfs root for my user .... I'm on centos6.2 CDH4 and sun java. I have no issue getting Hbase to work as a backend, but I need hdfs to import some RDF into Titan w/hbase through faunus .... Any thoughts? I have configured my hadoop environment variables to point at the cloudera parcels directory, and I'm able to run hbase shell on the machine. 

Here is a warning I'm getting when running the copy from local: 
13/06/20 16:13:02 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

**Comment by AlexanderDaw** [comment]
Bit of additional info here... so it looks like I've configured something wrong here,,, just not sure what....
gremlin> hdfs
==>org.apache.hadoop.fs.LocalFileSystem@3857dc15

**Comment by okram** [comment]
This is not an issue with Faunus, but with your Hadoop configuration. Please be sure to have a reference to your cluster in your HADOOP_CONF properties. Review the Hadoop documentation for the proper way to set up a Hadoop cluster. Good luck.

**Comment by AlexanderDaw** [comment]
I have set the HADOOP_CONF_DIR correctly and am able to run hadoop dfs commands from the shell as well as map reduce jobs from the node. On gremlin startup I see that my hadoop conf dir has been added to the cp. running hdfs.ls() in the shell produces my local user root directory. running hadoop dfs -ls from outside of gremlin products the listing for the remote hdfs user root. 

gremlin> hdfs.ls()
==>rw-r--r-- hdfs hdfs 18 .bash_logout
==>rw-r--r-- hdfs hdfs 176 .bash_profile
==>rw-r--r-- hdfs hdfs 124 .bashrc
==>rw-rw-r-- hdfs hdfs 129 .gremlin_faunus_history
==>rwxrwxr-x hdfs hdfs 4096 (D) .java
==>rwxrw---- hdfs hdfs 4096 (D) .pki

[]$:hadoop dfs -ls
Found 4 items
drwxr-xr-x   - hdfs supergroup          0 2013-06-22 17:00 .Trash
drwx------   - hdfs supergroup          0 2013-06-28 08:34 .staging
drwxr-xr-x   - hdfs supergroup          0 2013-06-28 08:24 input
drwxr-xr-x   - hdfs supergroup          0 2013-06-28 08:34 output

Centos6.2, cloudera CDH 4.3.0-1.cdh4.3.0.p0.22

**Comment by okram** [comment]
What version of Faunus? Can you figure out a patch that works for you? If so, I can merge.

**Comment by AlexanderDaw** [comment]
faunus-0.3.1 . I can take a stab at it, just wanted to make sure that I wasn't using it wrong.... and that it wasn't a known issue.

**Comment by akbarsh** [comment]
Any update on this? Am seeing the same isuue. Thanks!

**Comment by davidnarayan** [comment]
Try running gremlin.sh with the HADOOP_CONF or HADOOP_CONF_DIR environment variable set in your shell. 

Example:

```
[root@hdp1 faunus-0.3.1]# HADOOP_CONF=/etc/hadoop/conf bin/gremlin.sh
gremlin> hdfs
==>DFS[DFSClient[clientName=DFSClient_NONMAPREDUCE_725115163_1, ugi=root]]
```

**Comment by carlosalberto** [comment]
I confirm this 'bug' to appear using Faunus 0.4.0 - and also, specifying the conf directory using HADOOP_CONF made the trick.

That being said, looks like by default Faunus/Gremlin tried to detect the conf dir itself - which at least in Mac fails, since it is in a not-so-common directory, i.e. /usr/local/Cellar/hadoop/

_Maybe_ there's no way to 'fix' this, other than ask the user to export such conf location, but then it would be a good idea to mention that in the docs.

**Comment by okram** [comment]
It says it in Getting Started:
  https://github.com/thinkaurelius/faunus/wiki/Getting-Started

**Comment by carlosalberto** [comment]
Quoting: "For more experienced Hadoop users, the examples below can be easily adapted to work with a non-local Hadoop cluster (e.g. simply change the Hadoop configuration to point to the accessible cluster ($HADOOP_CONF_DIR)." 

Maybe mentioning that for a local Hadoop cluster it may be needed, too? (Since running without such env var just prints no error...)
