### ISSUE TITLE
Add Support for AWS Elastic MapReduce to Simplify Hadoop Cluster Management

### ISSUE THREAD

**Issue by espeed** [thinkaurelius/faunus#132]
Amazon Elastic MapReduce (EMR)
http://aws.amazon.com/elasticmapreduce/

EMR is used by a ton of companies because it simplifies the whole Hadoop process so a Faunus-EMR adapter would have wide appeal.

You can add a custom JAR...

http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-cluster-type.html

See "Run a Hadoop Application to Process Data"...

http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-hadoop-application.html

You can create Boostrap Actions to install additional software...

http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-bootstrap.html

You could also consider setting up Faunus as a third-party tool:

http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-third-party.html

**Comment by okram** [comment]
Will not do. If someone wants to they can deal with this.
