### ISSUE TITLE
gremlin.sh's -e switch does not run the script

### ISSUE THREAD

**Issue by szarnyasg** [thinkaurelius/faunus#137]
The `-e` switch does not run the command. Tested on Ubuntu Linux with Faunus 0.3.1, 0.3.2 and the current 0.4.0-SNAPSHOT.

Example:

```
$ cp data/graph-of-the-gods.json .
$ cat script.txt
g = FaunusFactory.open('bin/faunus.properties');
g.V.type.groupCount;
$ bin/gremlin.sh -e script.txt
$ bin/gremlin.sh < script.txt

         \,,,/
         (o o)
-----oOOo-(_)-oOOo-----
gremlin> g = FaunusFactory.open('bin/faunus.properties');
==>faunusgraph[graphsoninputformat->graphsonoutputformat]
gremlin> g.V.type.groupCount;
...
==>demigod  1
==>god  3
==>human    1
==>location 3
==>monster  3
==>titan    1
```

For more complicated scripts, it's clearly observable that the command with the `-e` switch does not run the script (instead, it finishes instantly).

**Comment by dkuppitz** [comment]
See [Gremlin Script](https://github.com/thinkaurelius/faunus/wiki/Command-Line-Usage#gremlin-script)

> Note that `FaunusPipeline.submit()` is required to ultimately submit the job to the Hadoop cluster. In the Gremlin REPL, this is handled for the user automatically.

**Comment by szarnyasg** [comment]
Thanks, that makes perfect sense. Using `g.V.type.groupCount.submit();` did the trick.
