### ISSUE TITLE
No access to HDFS in Gremlin Scripts

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/faunus#141]
When you start a Gremlin Script via `bin/gremlin.sh -e script.groovy`, your script may currently not contain `hdfs.anything(...)`. Would be good to have this available.

**Comment by okram** [comment]
Fixed.

```
~/software/aurelius/faunus$ bin/gremlin.sh -e Script.groovy
2013-09-24 12:33:13.334 java[6447:1703] Unable to load realm info from SCDynamicStore
DFS[DFSClient[clientName=DFSClient_NONMAPREDUCE_949022069_1, ugi=marko]]
```

Will be available in master/ on next push.
