### ISSUE TITLE
Can Faunus keep mapred job results in HDFS?

### ISSUE THREAD

**Issue by zhynxn** [thinkaurelius/faunus#148]
Instead of fixed output location, ie. output/job-0, it is better to use job id as the sub-folder name

**Comment by okram** [comment]
After trying to implement this, I realized that there is no JOB-ID assigned to a job prior to its submission to the Hadoop cluster. Thus, all the HDFS directory prepwork can't have access to the JOB-ID. Will close now with a "WONT FIX," but if you figure out a way to implement his, please provide a pull request.
