### ISSUE TITLE
Running faunus jobs periodically.?

### ISSUE THREAD

**Issue by kvk2105** [thinkaurelius/faunus#155]
Is there any way to run faunus jobs periodically .?
Clearly,Is there any mechanism/approach to tackle a scenario, where a faunus job has to read two .json files periodically and update the titan graph accordingly based on the content of the json files. Here the back store for titan is hbase.

**Comment by spmallette** [comment]
in the future, please post "how to" questions to the aurelius graphs mailing list: 

https://groups.google.com/forum/#!forum/aureliusgraphs

as a quick answer to your question, faunus does not supply a way to do that out-of-the-box and we are still working with customers to understand the best practices and patterns for doing so.  some options for doing this include scripting with chron jobs, triggering jobs via the Faunus Executor Rexster Extension (https://github.com/thinkaurelius/faunus/wiki/Rexster-Usage), etc.

**Comment by kvk2105** [comment]
Thank you for the info as well as directing me to the correct mailing list.
