### ISSUE TITLE
Update hadoop single node cluster setup link

### ISSUE THREAD

**Issue by astubbs** [thinkaurelius/faunus#156]
should be http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/SingleNodeSetup.html

on page https://github.com/thinkaurelius/faunus/wiki/Getting-Started
... EC2 (see the following tutorial) o....

**Comment by astubbs** [comment]
actually, those seem out of date for the 2.x version of hadoop too :/

**Comment by astubbs** [comment]
Ah, I see now that faunus 4.0 isn't compatible with hadoop 2. Would be could to mention that on the quickstart page, as hadoop2 is quite predominately featured for download. Link still needs updating though:
http://hadoop.apache.org/docs/current1/single_node_setup.html

**Comment by okram** [comment]
Done. Thanks.
