### ISSUE TITLE
Make BlueprintsGraphReader/Writer and Input/OutputFormats.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#16]
Would be serial, on the initial load, but once in Hadoop, all operations are parallel.

**Comment by okram** [comment]
This should actually be via Rexster as Hadoop will need to pull this over the wire. Therefore a RexsterReader/Writer and RexsterInput/OutputFormat.

**Comment by spmallette** [comment]
Would be cool if this could tie into a revised super speedy RexPro.

**Comment by okram** [comment]
https://github.com/thinkaurelius/faunus/tree/master/src/main/java/com/thinkaurelius/faunus/formats

**Comment by okram** [comment]
Via RexPro, use the binary representation of a FaunusVertex to send the binary representation over the wire as a Hadoop DataInput.

@spmallette recommended that we make this a Kibble. What is cool is that if we do this, then you simply drop the faunus.jar in your Rexster /ext and BAM, you can start sucking your graph.getVertices() iterator across the wire in Faunus-ready binary format.

**Comment by okram** [comment]
Done. Thanks @spmallette
