### ISSUE TITLE
Faunus Ignoring cassandra.input.split.size 

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/faunus#163]
Setting `cassandra.input.split.size` doesn't seem to affect faunus jobs.  I would expect that setting to create more tasks for the mappers to handle, but it doesn't seem to do that.

**Comment by okram** [comment]
Can you please say more about the job you are trying to do -- input format, output format, and intermediate MapReduce steps (i.e., Gremlin steps).

**Comment by spmallette** [comment]
Here's `faunus.properties` for this specific case:

``` text
# input graph parameters
faunus.graph.input.format=com.thinkaurelius.faunus.formats.titan.cassandra.TitanCassandraInputFormat
faunus.graph.input.titan.storage.backend=cassandra
faunus.graph.input.titan.storage.hostname=xxx.xxx.xxx.xxxx
faunus.graph.input.titan.storage.port=9160
faunus.graph.input.titan.storage.keyspace=titan
faunus.graph.input.titan.storage.connection-timeout=60000
faunus.graph.input.titan.storage.connection-pool-size=16
cassandra.input.partitioner.class=org.apache.cassandra.dht.RandomPartitioner
cassandra.input.split.size=16
cassandra.thrift.framed.size_mb=50
cassandra.thrift.message.max_size_mb=51

# output data (graph or statistic) parameters
faunus.graph.output.format=org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat
faunus.sideeffect.output.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
faunus.output.location=snapshot
faunus.output.location.overwrite=true

mapred.map.child.java.opts=-Xmx3072M
mapred.max.tracker.failures=16
mapred.map.max.attempts=8
mapred.reduce.max.attempts=8
```

Note that I set `cassandra.input.split.size` to something really small (because my test data set was kinda small):

``` text
cassandra.input.split.size=16
```

I just want to do a `g._()` where I can reduce the size of these arguments:

``` text
cassandra.thrift.framed.size_mb=50
cassandra.thrift.message.max_size_mb=51
```

as in production they are much larger at 384 and growing.  I thought that by increasing the number of map tasks i could lower those numbers.  Even if that's not what can happen, it doesn't seem that setting the split size to 16 does much of anything, as i still end up with 4 tasks (which is what i get if if i don't set that value at all.  

I've also seen this value seemingly ignored on larger datasets as well...not just this test data.

@dkuppitz do you have anything to add?  you mentioned that you'd seen this issue too.

**Comment by spmallette** [comment]
meh...this seems to do stuff now.................maybe this was never a problem.
