### ISSUE TITLE
Missing tag for 0.4.4

### ISSUE THREAD

**Issue by erickt** [thinkaurelius/faunus#173]
It looks like Faunus 0.4.4 got released according to https://github.com/thinkaurelius/faunus/wiki/Downloads, but the released version hasn't been tagged in git. I assume the released version is https://github.com/thinkaurelius/faunus/commit/f7f7a11dabc60a931c65da8b092ea6be6eac3f75, so can someone create a tag to point at this commit? Thanks.

**Comment by okram** [comment]
@dalaro, can you tag this please?

**Comment by dalaro** [comment]
@erickt was right about the version.  I had the tag local but failed to push it.  Just pushed.
