### ISSUE TITLE
Improve the memory efficicency of GraphSONRecordReader

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#30]
As it stands, there are three representations of the same information in memory at every record parse:
1. the String of the record (up to \n)
2. the JSONObject representation of the String
3. the FaunusVertex representation of the JSONObject

If we could go from String -> FaunsVertex, that would be good. However, the best would be InputStreamReader -> FaunusVertex.

**Comment by okram** [comment]
@spmallette This is all ready for you. Please close ticket when done. Thanks man.

**Comment by okram** [comment]
Is this done?

**Comment by spmallette** [comment]
it's done for purposes of what can be done with 2.2 of blueprints.  so, certain things got better, but it's still not as efficient as it could be.  i'd leave it open.  need one more evolution of changes to graphson to get it perfect i think.

**Comment by spmallette** [comment]
given current use of Jettison for JSON processing which doesn't take an InputStream to the JSONTokener, I'm not sure i'm seeing any more that can be done with this using the Blueprints GraphSONUtility.  I could use a different JSON parser and/or then maybe write a custom GraphSON reader just for Faunus, but perhaps not worth the effort and additional code to maintain.  closing for now...please re-open if these steps need to be taken.
