### ISSUE TITLE
Faunus - Titan:BerkeleyJE Adapter

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/faunus#39]
We might also be able to accomodate that through Rexster.

**Comment by okram** [comment]
@spmallette can you check to make sure this works... I don't see why it wouldn't. If you are happy with it, please close issue.

**Comment by spmallette** [comment]
This doesn't work.  titan has non-long identifiers for edges, like:

57:8:36028797018964014

I would need to build a custom id handler like i did for orientdb that converts these to long.  @mbroecheler is this possible?

**Comment by mbroecheler** [comment]
If you convert an edge to TitanEdge you can call getID() [with uppercase D]
to get the edge long id. This id is not de-referencable.

On Wed, Sep 19, 2012 at 8:11 AM, stephen mallette
notifications@github.comwrote:

> This doesn't work. titan has non-long identifiers for edges, like:
> 
> 57:8:36028797018964014
> 
> I would need to build a custom id handler like i did for orientdb that
> converts these to long. @mbroecheler https://github.com/mbroecheler is
> this possible?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/faunus/issues/39#issuecomment-8694010.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by spmallette** [comment]
implemented an identifier handler.  good to go....
