### ISSUE TITLE
Remove as many "news" as possible in Titan adaptor.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#46]
FaunusVertexRelationLoader loader = new FaunusVertexRelationLoader(IDHandler.getKeyID(row.left.duplicate()));

```
public FaunusVertexRelationLoader(final long id) {
    Preconditions.checkArgument(id > 0);
    vertex = new FaunusVertex(id);
}
```

**Comment by mbroecheler** [comment]
@okram What do you want me to do here? Are you concerned that we are creating to many objects? That's become a fairly cheap operation on modern jvms.

**Comment by okram** [comment]
K. Then Close.

Marko.

http://markorodriguez.com
