### ISSUE TITLE
Make respective .bats for .shs...

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#47]
gremlin.bat is basically identical to other gremlin.bat files save we now have -i parameter.

**Comment by okram** [comment]
@spmallette Can you hook this up before Wednesday night?

**Comment by spmallette** [comment]
it's been on my radar, but my one concern is how to test.  For whatever reason, hadoop hasn't worked well on my windows system.  All my development has been done on linux.  I'll see what i can do.

**Comment by spmallette** [comment]
Seems to be working, but couldn't fully confirm given hadoop environmental problems in my local windows instance.
