### ISSUE TITLE
Use static Strings dependencies (in Titan?) for Titan/Faunus connectors.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#65]
```
    titanconfig.setProperty("storage.backend", "cassandra");   // todo: astyanax
    titanconfig.setProperty("storage.hostname", ConfigHelper.getInputInitialAddress(config));
    titanconfig.setProperty("storage.keyspace", ConfigHelper.getInputKeyspace(config));
    titanconfig.setProperty("storage.port", ConfigHelper.getInputRpcPort(config));
```

Should be:

```
   TitanTokens.STORAGE_BACKEND 
```

**Comment by okram** [comment]
Also, no longer did EDGESTORE_NAME_DEFAULT exist anymore, but I found a static reference to "edgestore" in Backend.EDSTORE_NAME.. Is this okay?

https://github.com/thinkaurelius/faunus/blob/master/src/main/java/com/thinkaurelius/faunus/formats/titan/cassandra/TitanCassandraInputFormat.java#L47

https://github.com/thinkaurelius/faunus/blob/master/src/main/java/com/thinkaurelius/faunus/formats/titan/hbase/TitanHBaseInputFormat.java#L27

https://github.com/thinkaurelius/faunus/blob/master/src/main/java/com/thinkaurelius/faunus/formats/titan/hbase/TitanHBaseInputFormat.java#L51

**Comment by mbroecheler** [comment]
The configuration related tokens are defined in https://github.com/thinkaurelius/titan/blob/master/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/configuration/GraphDatabaseConfiguration.java

**Comment by okram** [comment]
Done.
