### ISSUE TITLE
New method in FaunusVertexRelationLoader with unknown behavior...?

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#70]
@mbroecheler -- I couldn't build Faunus without providing an implementation of the method listed below. The method does nothing as I have it now. Seems to work (tests pass). Does it need to do something?

https://github.com/thinkaurelius/faunus/blob/master/src/main/java/com/thinkaurelius/faunus/formats/titan/FaunusVertexRelationLoader.java#L94

**Comment by mbroecheler** [comment]
@okram This method is used inside Titan to connect a loaded edge in the in-heap object graph that is created for a transaction. For Faunus we are adding it immediately, so this should work fine. Nothing wrong here.
