### ISSUE TITLE
Support for incremental loading and graph mutations.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#78]
We now support bulk loading into Titan. What would be nice (and is currently not supported) is the ability to mutate elements in Titan using Faunus. For instance.

TitanXXXInputFormat ---> addVertices --> addEdges --> changeProperties --> TitanXXXOutputFormat

Where the InputFormat 'keyspace/table' is the same as the OutputFormat 'keyspace/table'

Off the top of my head, this is how this works:
1. For mutation properties on vertices and edges, this is trivial. (id of vertex/edge allows lookup and set/remove/etc. operations on that)
2. Adding/removing edges is simply checking for (non)existence by id... might be intensive, but possible.
3. Adding vertices......... ?  Can't think how this would work.

**Comment by mbroecheler** [comment]
When you initially load the graph the source id should be kept around so
that adding edges/properties does not require any lookups at the end.
Then, all faunus vertices that don't have a source id are new vertices and
hence need to be added to the graph in vertex-adding-phase of the bulk
loading. After that, all new edges and properties are added.
However, how do we know which edges are deleted (and how do we keep them
around). Similarly, how to do that for properties?

On Thu, Jan 3, 2013 at 7:01 PM, Marko A. Rodriguez <notifications@github.com

> wrote:
> 
> We now support bulk loading into Titan. What would be nice (and is
> currently not supported) is the ability to mutate elements in Titan using
> Faunus. For instance.
> 
> TitanXXXInputFormat ---> addVertices --> addEdges --> changeProperties -->
> TitanXXXOutputFormat
> 
> Where the InputFormat 'keyspace/table' is the same as the OutputFormat
> 'keyspace/table'
> 
> Off the top of my head, this is how this works:
> 1. For mutation properties on vertices and edges, this is trivial. (id
>    of vertex/edge allows lookup and set/remove/etc. operations on that)
> 2. Adding/removing edges is simply checking for (non)existence by
>    id... might be intensive, but possible.
> 3. Adding vertices......... ? Can't think how this would work.
>    
>    —
>    Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/faunus/issues/78.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by mbroecheler** [comment]
For incremental updates, we need some flag on the edges, properties which indicates whether that edges is new or deleted so that the corresponding mutation can be executed against titan at the end. That should address the last issue.

**Comment by okram** [comment]
See #108

**Comment by okram** [comment]
Work on IncremetalBlueprintsGraphOutputMap .. A map only task that has this behavior:

```
 @Override
        public void map(final NullWritable key, final FaunusVertex value, final Mapper<NullWritable, FaunusVertex, NullWritable, FaunusVertex>.Context context) throws IOException, InterruptedException {
            final Vertex vertex = this.getOrCreateVertex(value);
            for (final Edge faunusEdge : value.getEdges(Direction.OUT)) {
                final Vertex otherVertex = this.getOrCreateVertex(faunusEdge.getVertex(Direction.IN));
                final Edge edge = vertex.addEdge(faunusEdge.getLabel(), otherVertex);
                ElementHelper.copyProperties(faunusEdge, edge);
            }
        }
```
