### ISSUE TITLE
Titan needs schema generation Map in its OutputFormat

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#79]
@mbroecheler Can you provide me some psedocode of what this is all about... like:

// collect all the edge properties seen and their type.
// collect all the edge labels
// ...

for all unique edge labels, g.makeType()...
for all .......

**Comment by mbroecheler** [comment]
// collect all property keys in K (set of strings)
// collect all edge labels in L (set of strings)

DefaultTypeMaker tm = BlueprintsDefaultTypeMaker.INSTANCE;

for (String k : K) if (g.getType(k)==null) tm.makeKey(k,g.makeType());

for (String l : L) if (g.getType(l)==null) tm.makeLabel(l,g.makeType());

Its important that the tm.makeXYZ calls only occur once for each key and
label.

On Thu, Jan 3, 2013 at 7:10 PM, Marko A. Rodriguez <notifications@github.com

> wrote:
> 
> @mbroecheler https://github.com/mbroecheler Can you provide me some
> psedocode of what this is all about... like:
> 
> // collect all the edge properties seen and their type.
> // collect all the edge labels
> // ...
> 
> for all unique edge labels, g.makeType()...
> for all .......
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/faunus/issues/79.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by okram** [comment]
A reducer -1 id value "special metadata vertex"

**Comment by okram** [comment]
Done.
