### ISSUE TITLE
GraphSONOutputFormat not writing edge labels.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/faunus#86]
Hi,

This is something new. I suspect from our GraphSON work since 2.2.0 release:

---happening somewhere from here:
   this.out.write(GraphSONUtility.toJSON(vertex).toString().getBytes(UTF8));

gremlin> hdfs.head('output')
==>{"name":"saturn","type":"titan","_id":0,"_inE":[{"_id":12,"_outV":1}]}
==>{"name":"jupiter","type":"god","_id":1,"_outE":[{"_id":13,"_inV":4},{"_id":16,"_inV":3},{"_id":14,"_inV":2},{"_id":12,"_inV":0}],"_inE":[{"_id":17,"_outV":3},{"_id":15,"_outV":2},{"_id":24,"_outV":7}]}
==>{"name":"neptune","type":"god","_id":2,"_outE":[{"_id":20,"_inV":5},{"_id":19,"_inV":3},{"_id":15,"_inV":1}],"_inE":[{"_id":18,"_outV":3},{"_id":14,"_outV":1}]}
==>{"name":"pluto","type":"god","_id":3,"_outE":[{"_id":23,"_inV":11},{"_id":21,"_inV":6},{"_id":17,"_inV":1},{"_id":18,"_inV":2}],"_inE":[{"_id":19,"_outV":2},{"_id":16,"_outV":1}]}
==>{"name":"sky","type":"location","_id":4,"_inE":[{"_id":13,"_outV":1}]}
==>{"name":"sea","type":"location","_id":5,"_inE":[{"_id":20,"_outV":2}]}
==>{"name":"tartarus","type":"location","_id":6,"_inE":[{"_id":21,"_outV":3},{"_id":22,"_outV":11}]}
==>{"name":"hercules","type":"demigod","_id":7,"_outE":[{"_id":25,"_inV":8},{"time":1,"_id":26,"_inV":9},{"time":2,"_id":27,"_inV":10},{"time":12,"_id":28,"_inV":11},{"_id":24,"_inV":1}]}
==>{"name":"alcmene","type":"human","_id":8,"_inE":[{"_id":25,"_outV":7}]}
==>{"name":"nemean","type":"monster","_id":9,"_inE":[{"time":1,"_id":26,"_outV":7}]}
==>{"name":"hydra","type":"monster","_id":10,"_inE":[{"time":2,"_id":27,"_outV":7}]}
==>{"name":"cerberus","type":"monster","_id":11,"_outE":[{"_id":22,"_inV":6}],"_inE":[{"_id":23,"_outV":3},{"time":12,"_id":28,"_outV":7}]}

**Comment by okram** [comment]
Its crazy, we have a test case for GraphSONUTility writer, but don't actually test for _label!

GraphSONUtilityTest {
public void testWriter1() throws Exception { }
}

**Comment by spmallette** [comment]
fixed...and test updated.
